version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=smartwatt_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - SPRING_FLYWAY_ENABLED=true
      - JWT_SECRET=minha-chave-secreta-super-segura-para-producao
    depends_on:
      db:
        condition: service_healthy 
    networks:
      - app-network

  db:
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=rootpassword
      - APP_USER=smartwatt_user
      - APP_USER_PASSWORD=password
    volumes:
      - db-data:/opt/oracle/oradata
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  db-data: